matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode9.1
      language: generic

install:
 - travis_retry wget https://github.com/quodlibet/quodlibet/releases/download/release-4.0.0/QuodLibet-4.0.0.dmg
 - hdiutil attach -readonly -mountpoint _mount QuodLibet-4.0.0.dmg

script:
 - cd quodlibet
 - ../_mount/QuodLibet.app/Contents/MacOS/run -R -bb -m coverage run --branch setup.py test
 - ../_mount/QuodLibet.app/Contents/MacOS/run -R -bb -m coverage xml
 - bash <(curl -s https://codecov.io/bash)
